name: kickr_flutter
description: A Flutter web application for controlling a Wahoo Kickr bike trainer.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  file_picker: ^5.3.3
  gpx: ^2.2.1
  shared_preferences: ^2.2.0
  fl_chart: ^0.63.0
  equatable: ^2.0.5
  xml: ^6.3.0 # gpx might need this, but good to have explicitly

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true